### ISSUE TITLE
List out currently pending PublicationRequests

### ISSUE THREAD

**Issue by natyconnor** [Via-Bahia-Dev/pubs-portal-front-end#13]
Make a nice `index` for `PublicationRequests`. This can be somewhat experimental, since we don't know where in the workflow this will be used, but we know we'll need it eventually. Can try things with thumbnails of images and fancy javascript stuff like [Freewall](http://vnjs.net/www/project/freewall/)

**Comment by dwosk** [comment]
will list all publication requests. can implement filter by option later

**Comment by dwosk** [comment]
`publication_requests GET          /publication_requests(.:format)         publication_requests#index`

**Comment by natyconnor** [comment]
Just have a small thumbnail on home page for now. Working on show page now

**Comment by natyconnor** [comment]
Index uses [Isotope](http://packery.metafizzy.co/extras.html) for grid layout and filtering. Hard coded filters for now. May look into being able to create custom filters.
