### ISSUE TITLE
make publication request controller / model

### ISSUE THREAD

**Issue by dwosk** [Via-Bahia-Dev/pubs-portal-front-end#3]

**Comment by dwosk** [comment]
thinking some type of form that will submit post request to api side

**Comment by natyconnor** [comment]
I would make it on the api side first, test with curl or something, and then move on to the front end. That's what I did with `Users`

**Comment by dwosk** [comment]
api side - create, update, destroy - DONE
frontend - TODO

**Comment by dwosk** [comment]
im going to make new issue close this one out
